/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Odata response wrapper for audit activity events list
 */
@ApiModel(description = "Odata response wrapper for audit activity events list")
@JsonPropertyOrder({ ActivityEventResponse.JSON_PROPERTY_ACTIVITY_EVENT_ENTITIES,
        ActivityEventResponse.JSON_PROPERTY_CONTINUATION_URI, ActivityEventResponse.JSON_PROPERTY_CONTINUATION_TOKEN })

public class ActivityEventResponse {
    public static final String JSON_PROPERTY_ACTIVITY_EVENT_ENTITIES = "activityEventEntities";
    private List<Object> activityEventEntities = null;

    public static final String JSON_PROPERTY_CONTINUATION_URI = "continuationUri";
    private String continuationUri;

    public static final String JSON_PROPERTY_CONTINUATION_TOKEN = "continuationToken";
    private String continuationToken;

    public ActivityEventResponse activityEventEntities(List<Object> activityEventEntities) {

        this.activityEventEntities = activityEventEntities;
        return this;
    }

    public ActivityEventResponse addActivityEventEntitiesItem(Object activityEventEntitiesItem) {
        if (this.activityEventEntities == null) {
            this.activityEventEntities = new ArrayList<>();
        }
        this.activityEventEntities.add(activityEventEntitiesItem);
        return this;
    }

    /**
     * The activity event entities
     * 
     * @return activityEventEntities
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The activity event entities")
    @JsonProperty(JSON_PROPERTY_ACTIVITY_EVENT_ENTITIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<Object> getActivityEventEntities() {
        return activityEventEntities;
    }

    public void setActivityEventEntities(List<Object> activityEventEntities) {
        this.activityEventEntities = activityEventEntities;
    }

    public ActivityEventResponse continuationUri(String continuationUri) {

        this.continuationUri = continuationUri;
        return this;
    }

    /**
     * Uri to get the next chunk of the result set
     * 
     * @return continuationUri
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Uri to get the next chunk of the result set")
    @JsonProperty(JSON_PROPERTY_CONTINUATION_URI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getContinuationUri() {
        return continuationUri;
    }

    public void setContinuationUri(String continuationUri) {
        this.continuationUri = continuationUri;
    }

    public ActivityEventResponse continuationToken(String continuationToken) {

        this.continuationToken = continuationToken;
        return this;
    }

    /**
     * Token to get the next chunk of the result set
     * 
     * @return continuationToken
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Token to get the next chunk of the result set")
    @JsonProperty(JSON_PROPERTY_CONTINUATION_TOKEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getContinuationToken() {
        return continuationToken;
    }

    public void setContinuationToken(String continuationToken) {
        this.continuationToken = continuationToken;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ActivityEventResponse activityEventResponse = (ActivityEventResponse) o;
        return Objects.equals(this.activityEventEntities, activityEventResponse.activityEventEntities)
                && Objects.equals(this.continuationUri, activityEventResponse.continuationUri)
                && Objects.equals(this.continuationToken, activityEventResponse.continuationToken);
    }

    @Override
    public int hashCode() {
        return Objects.hash(activityEventEntities, continuationUri, continuationToken);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ActivityEventResponse {\n");
        sb.append("    activityEventEntities: ").append(toIndentedString(activityEventEntities)).append("\n");
        sb.append("    continuationUri: ").append(toIndentedString(continuationUri)).append("\n");
        sb.append("    continuationToken: ").append(toIndentedString(continuationToken)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
