/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A Power BI Installed App
 */
@ApiModel(description = "A Power BI Installed App")
@JsonPropertyOrder({ App.JSON_PROPERTY_ID, App.JSON_PROPERTY_NAME, App.JSON_PROPERTY_DESCRIPTION,
        App.JSON_PROPERTY_LAST_UPDATE, App.JSON_PROPERTY_PUBLISHED_BY })

public class App {
    public static final String JSON_PROPERTY_ID = "id";
    private UUID id;

    public static final String JSON_PROPERTY_NAME = "name";
    private String name;

    public static final String JSON_PROPERTY_DESCRIPTION = "description";
    private String description;

    public static final String JSON_PROPERTY_LAST_UPDATE = "lastUpdate";
    private OffsetDateTime lastUpdate;

    public static final String JSON_PROPERTY_PUBLISHED_BY = "publishedBy";
    private String publishedBy;

    public App id(UUID id) {

        this.id = id;
        return this;
    }

    /**
     * The app id
     * 
     * @return id
     **/
    @ApiModelProperty(required = true, value = "The app id")
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public App name(String name) {

        this.name = name;
        return this;
    }

    /**
     * The app name
     * 
     * @return name
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The app name")
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public App description(String description) {

        this.description = description;
        return this;
    }

    /**
     * The app description
     * 
     * @return description
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The app description")
    @JsonProperty(JSON_PROPERTY_DESCRIPTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public App lastUpdate(OffsetDateTime lastUpdate) {

        this.lastUpdate = lastUpdate;
        return this;
    }

    /**
     * The last time the app was updated
     * 
     * @return lastUpdate
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The last time the app was updated")
    @JsonProperty(JSON_PROPERTY_LAST_UPDATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(OffsetDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public App publishedBy(String publishedBy) {

        this.publishedBy = publishedBy;
        return this;
    }

    /**
     * The app publisher
     * 
     * @return publishedBy
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The app publisher")
    @JsonProperty(JSON_PROPERTY_PUBLISHED_BY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPublishedBy() {
        return publishedBy;
    }

    public void setPublishedBy(String publishedBy) {
        this.publishedBy = publishedBy;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        App app = (App) o;
        return Objects.equals(this.id, app.id) && Objects.equals(this.name, app.name)
                && Objects.equals(this.description, app.description) && Objects.equals(this.lastUpdate, app.lastUpdate)
                && Objects.equals(this.publishedBy, app.publishedBy);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, description, lastUpdate, publishedBy);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class App {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    lastUpdate: ").append(toIndentedString(lastUpdate)).append("\n");
        sb.append("    publishedBy: ").append(toIndentedString(publishedBy)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
