/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Request body for assigning workspaces to a premium capacity as tenant admin
 */
@ApiModel(description = "Request body for assigning workspaces to a premium capacity as tenant admin")
@JsonPropertyOrder({ AssignWorkspacesToCapacityRequest.JSON_PROPERTY_CAPACITY_MIGRATION_ASSIGNMENTS })

public class AssignWorkspacesToCapacityRequest {
    public static final String JSON_PROPERTY_CAPACITY_MIGRATION_ASSIGNMENTS = "capacityMigrationAssignments";
    private List<CapacityMigrationAssignment> capacityMigrationAssignments = new ArrayList<>();

    public AssignWorkspacesToCapacityRequest capacityMigrationAssignments(
            List<CapacityMigrationAssignment> capacityMigrationAssignments) {

        this.capacityMigrationAssignments = capacityMigrationAssignments;
        return this;
    }

    public AssignWorkspacesToCapacityRequest addCapacityMigrationAssignmentsItem(
            CapacityMigrationAssignment capacityMigrationAssignmentsItem) {
        this.capacityMigrationAssignments.add(capacityMigrationAssignmentsItem);
        return this;
    }

    /**
     * Get capacityMigrationAssignments
     * 
     * @return capacityMigrationAssignments
     **/
    @ApiModelProperty(required = true, value = "")
    @JsonProperty(JSON_PROPERTY_CAPACITY_MIGRATION_ASSIGNMENTS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public List<CapacityMigrationAssignment> getCapacityMigrationAssignments() {
        return capacityMigrationAssignments;
    }

    public void setCapacityMigrationAssignments(List<CapacityMigrationAssignment> capacityMigrationAssignments) {
        this.capacityMigrationAssignments = capacityMigrationAssignments;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AssignWorkspacesToCapacityRequest assignWorkspacesToCapacityRequest = (AssignWorkspacesToCapacityRequest) o;
        return Objects.equals(this.capacityMigrationAssignments,
                assignWorkspacesToCapacityRequest.capacityMigrationAssignments);
    }

    @Override
    public int hashCode() {
        return Objects.hash(capacityMigrationAssignments);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AssignWorkspacesToCapacityRequest {\n");
        sb.append("    capacityMigrationAssignments: ").append(toIndentedString(capacityMigrationAssignments))
                .append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
