/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.Objects;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Power BI assign to Power BI dataflow storage account request
 */
@ApiModel(description = "Power BI assign to Power BI dataflow storage account request")
@JsonPropertyOrder({ AssignToDataflowStorageRequest.JSON_PROPERTY_DATAFLOW_STORAGE_ID })

public class AssignToDataflowStorageRequest {
    public static final String JSON_PROPERTY_DATAFLOW_STORAGE_ID = "dataflowStorageId";
    private UUID dataflowStorageId;

    public AssignToDataflowStorageRequest dataflowStorageId(UUID dataflowStorageId) {

        this.dataflowStorageId = dataflowStorageId;
        return this;
    }

    /**
     * The Power BI dataflow storage account id. To unassign the specified workspace
     * from a Power BI dataflow storage account, an empty GUID
     * (00000000-0000-0000-0000-000000000000) should be provided as
     * dataflowStorageId.
     * 
     * @return dataflowStorageId
     **/
    @ApiModelProperty(required = true, value = "The Power BI dataflow storage account id. To unassign the specified workspace from a Power BI dataflow storage account, an empty GUID (00000000-0000-0000-0000-000000000000) should be provided as dataflowStorageId.")
    @JsonProperty(JSON_PROPERTY_DATAFLOW_STORAGE_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public UUID getDataflowStorageId() {
        return dataflowStorageId;
    }

    public void setDataflowStorageId(UUID dataflowStorageId) {
        this.dataflowStorageId = dataflowStorageId;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AssignToDataflowStorageRequest assignToDataflowStorageRequest = (AssignToDataflowStorageRequest) o;
        return Objects.equals(this.dataflowStorageId, assignToDataflowStorageRequest.dataflowStorageId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(dataflowStorageId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AssignToDataflowStorageRequest {\n");
        sb.append("    dataflowStorageId: ").append(toIndentedString(dataflowStorageId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
