/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * The bind dataset to gateway request
 */
@ApiModel(description = "The bind dataset to gateway request")
@JsonPropertyOrder({ BindToGatewayRequest.JSON_PROPERTY_GATEWAY_OBJECT_ID,
        BindToGatewayRequest.JSON_PROPERTY_DATASOURCE_OBJECT_IDS })

public class BindToGatewayRequest {
    public static final String JSON_PROPERTY_GATEWAY_OBJECT_ID = "gatewayObjectId";
    private UUID gatewayObjectId;

    public static final String JSON_PROPERTY_DATASOURCE_OBJECT_IDS = "datasourceObjectIds";
    private List<UUID> datasourceObjectIds = null;

    public BindToGatewayRequest gatewayObjectId(UUID gatewayObjectId) {

        this.gatewayObjectId = gatewayObjectId;
        return this;
    }

    /**
     * The gateway id
     * 
     * @return gatewayObjectId
     **/
    @ApiModelProperty(required = true, value = "The gateway id")
    @JsonProperty(JSON_PROPERTY_GATEWAY_OBJECT_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public UUID getGatewayObjectId() {
        return gatewayObjectId;
    }

    public void setGatewayObjectId(UUID gatewayObjectId) {
        this.gatewayObjectId = gatewayObjectId;
    }

    public BindToGatewayRequest datasourceObjectIds(List<UUID> datasourceObjectIds) {

        this.datasourceObjectIds = datasourceObjectIds;
        return this;
    }

    public BindToGatewayRequest addDatasourceObjectIdsItem(UUID datasourceObjectIdsItem) {
        if (this.datasourceObjectIds == null) {
            this.datasourceObjectIds = new ArrayList<>();
        }
        this.datasourceObjectIds.add(datasourceObjectIdsItem);
        return this;
    }

    /**
     * datasourceObjectIds belonging to the gateway
     * 
     * @return datasourceObjectIds
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "datasourceObjectIds belonging to the gateway")
    @JsonProperty(JSON_PROPERTY_DATASOURCE_OBJECT_IDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<UUID> getDatasourceObjectIds() {
        return datasourceObjectIds;
    }

    public void setDatasourceObjectIds(List<UUID> datasourceObjectIds) {
        this.datasourceObjectIds = datasourceObjectIds;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BindToGatewayRequest bindToGatewayRequest = (BindToGatewayRequest) o;
        return Objects.equals(this.gatewayObjectId, bindToGatewayRequest.gatewayObjectId)
                && Objects.equals(this.datasourceObjectIds, bindToGatewayRequest.datasourceObjectIds);
    }

    @Override
    public int hashCode() {
        return Objects.hash(gatewayObjectId, datasourceObjectIds);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class BindToGatewayRequest {\n");
        sb.append("    gatewayObjectId: ").append(toIndentedString(gatewayObjectId)).append("\n");
        sb.append("    datasourceObjectIds: ").append(toIndentedString(datasourceObjectIds)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
