/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Assignment contract for migrating workspaces to shared capacity as tenant
 * admin
 */
@ApiModel(description = "Assignment contract for migrating workspaces to shared capacity as tenant admin")
@JsonPropertyOrder({ CapacityMigrationAssignment.JSON_PROPERTY_WORKSPACES_TO_ASSIGN,
        CapacityMigrationAssignment.JSON_PROPERTY_TARGET_CAPACITY_OBJECT_ID })

public class CapacityMigrationAssignment {
    public static final String JSON_PROPERTY_WORKSPACES_TO_ASSIGN = "workspacesToAssign";
    private List<String> workspacesToAssign = new ArrayList<>();

    public static final String JSON_PROPERTY_TARGET_CAPACITY_OBJECT_ID = "targetCapacityObjectId";
    private String targetCapacityObjectId;

    public CapacityMigrationAssignment workspacesToAssign(List<String> workspacesToAssign) {

        this.workspacesToAssign = workspacesToAssign;
        return this;
    }

    public CapacityMigrationAssignment addWorkspacesToAssignItem(String workspacesToAssignItem) {
        this.workspacesToAssign.add(workspacesToAssignItem);
        return this;
    }

    /**
     * Workspaces to be migrated to shared capacity
     * 
     * @return workspacesToAssign
     **/
    @ApiModelProperty(required = true, value = "Workspaces to be migrated to shared capacity")
    @JsonProperty(JSON_PROPERTY_WORKSPACES_TO_ASSIGN)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public List<String> getWorkspacesToAssign() {
        return workspacesToAssign;
    }

    public void setWorkspacesToAssign(List<String> workspacesToAssign) {
        this.workspacesToAssign = workspacesToAssign;
    }

    public CapacityMigrationAssignment targetCapacityObjectId(String targetCapacityObjectId) {

        this.targetCapacityObjectId = targetCapacityObjectId;
        return this;
    }

    /**
     * Capacity id
     * 
     * @return targetCapacityObjectId
     **/
    @ApiModelProperty(required = true, value = "Capacity id")
    @JsonProperty(JSON_PROPERTY_TARGET_CAPACITY_OBJECT_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getTargetCapacityObjectId() {
        return targetCapacityObjectId;
    }

    public void setTargetCapacityObjectId(String targetCapacityObjectId) {
        this.targetCapacityObjectId = targetCapacityObjectId;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CapacityMigrationAssignment capacityMigrationAssignment = (CapacityMigrationAssignment) o;
        return Objects.equals(this.workspacesToAssign, capacityMigrationAssignment.workspacesToAssign)
                && Objects.equals(this.targetCapacityObjectId, capacityMigrationAssignment.targetCapacityObjectId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(workspacesToAssign, targetCapacityObjectId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CapacityMigrationAssignment {\n");
        sb.append("    workspacesToAssign: ").append(toIndentedString(workspacesToAssign)).append("\n");
        sb.append("    targetCapacityObjectId: ").append(toIndentedString(targetCapacityObjectId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
