/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A Power BI capacity
 */
@ApiModel(description = "A Power BI capacity")
@JsonPropertyOrder({ Capacity.JSON_PROPERTY_ID, Capacity.JSON_PROPERTY_DISPLAY_NAME, Capacity.JSON_PROPERTY_ADMINS,
        Capacity.JSON_PROPERTY_SKU, Capacity.JSON_PROPERTY_STATE, Capacity.JSON_PROPERTY_CAPACITY_USER_ACCESS_RIGHT,
        Capacity.JSON_PROPERTY_REGION, Capacity.JSON_PROPERTY_TENANT_KEY_ID, Capacity.JSON_PROPERTY_TENANT_KEY })

public class Capacity {
    public static final String JSON_PROPERTY_ID = "id";
    private UUID id;

    public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
    private String displayName;

    public static final String JSON_PROPERTY_ADMINS = "admins";
    private List<String> admins = null;

    public static final String JSON_PROPERTY_SKU = "sku";
    private String sku;

    /**
     * The capacity state
     */
    public enum StateEnum {
        NOTACTIVATED("NotActivated"),

        ACTIVE("Active"),

        PROVISIONING("Provisioning"),

        PROVISIONFAILED("ProvisionFailed"),

        PRESUSPENDED("PreSuspended"),

        SUSPENDED("Suspended"),

        DELETING("Deleting"),

        DELETED("Deleted"),

        INVALID("Invalid"),

        UPDATINGSKU("UpdatingSku");

        private String value;

        StateEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static StateEnum fromValue(String value) {
            for (StateEnum b : StateEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_STATE = "state";
    private StateEnum state;

    /**
     * Access right user has on the capacity
     */
    public enum CapacityUserAccessRightEnum {
        NONE("None"),

        ASSIGN("Assign"),

        ADMIN("Admin");

        private String value;

        CapacityUserAccessRightEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static CapacityUserAccessRightEnum fromValue(String value) {
            for (CapacityUserAccessRightEnum b : CapacityUserAccessRightEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_CAPACITY_USER_ACCESS_RIGHT = "capacityUserAccessRight";
    private CapacityUserAccessRightEnum capacityUserAccessRight;

    public static final String JSON_PROPERTY_REGION = "region";
    private String region;

    public static final String JSON_PROPERTY_TENANT_KEY_ID = "tenantKeyId";
    private UUID tenantKeyId;

    public static final String JSON_PROPERTY_TENANT_KEY = "tenantKey";
    private TenantKey tenantKey;

    public Capacity id(UUID id) {

        this.id = id;
        return this;
    }

    /**
     * The capacity id
     * 
     * @return id
     **/
    @ApiModelProperty(required = true, value = "The capacity id")
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public Capacity displayName(String displayName) {

        this.displayName = displayName;
        return this;
    }

    /**
     * The capacity display name
     * 
     * @return displayName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The capacity display name")
    @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public Capacity admins(List<String> admins) {

        this.admins = admins;
        return this;
    }

    public Capacity addAdminsItem(String adminsItem) {
        if (this.admins == null) {
            this.admins = new ArrayList<>();
        }
        this.admins.add(adminsItem);
        return this;
    }

    /**
     * An array of capacity admins.
     * 
     * @return admins
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "An array of capacity admins.")
    @JsonProperty(JSON_PROPERTY_ADMINS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getAdmins() {
        return admins;
    }

    public void setAdmins(List<String> admins) {
        this.admins = admins;
    }

    public Capacity sku(String sku) {

        this.sku = sku;
        return this;
    }

    /**
     * The capacity SKU.
     * 
     * @return sku
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The capacity SKU.")
    @JsonProperty(JSON_PROPERTY_SKU)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public Capacity state(StateEnum state) {

        this.state = state;
        return this;
    }

    /**
     * The capacity state
     * 
     * @return state
     **/
    @ApiModelProperty(required = true, value = "The capacity state")
    @JsonProperty(JSON_PROPERTY_STATE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public StateEnum getState() {
        return state;
    }

    public void setState(StateEnum state) {
        this.state = state;
    }

    public Capacity capacityUserAccessRight(CapacityUserAccessRightEnum capacityUserAccessRight) {

        this.capacityUserAccessRight = capacityUserAccessRight;
        return this;
    }

    /**
     * Access right user has on the capacity
     * 
     * @return capacityUserAccessRight
     **/
    @ApiModelProperty(required = true, value = "Access right user has on the capacity")
    @JsonProperty(JSON_PROPERTY_CAPACITY_USER_ACCESS_RIGHT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public CapacityUserAccessRightEnum getCapacityUserAccessRight() {
        return capacityUserAccessRight;
    }

    public void setCapacityUserAccessRight(CapacityUserAccessRightEnum capacityUserAccessRight) {
        this.capacityUserAccessRight = capacityUserAccessRight;
    }

    public Capacity region(String region) {

        this.region = region;
        return this;
    }

    /**
     * The Azure region where the capacity is provisioned
     * 
     * @return region
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The Azure region where the capacity is provisioned")
    @JsonProperty(JSON_PROPERTY_REGION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public Capacity tenantKeyId(UUID tenantKeyId) {

        this.tenantKeyId = tenantKeyId;
        return this;
    }

    /**
     * The id of the encryption key (Only applicable for admin route)
     * 
     * @return tenantKeyId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The id of the encryption key (Only applicable for admin route)")
    @JsonProperty(JSON_PROPERTY_TENANT_KEY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UUID getTenantKeyId() {
        return tenantKeyId;
    }

    public void setTenantKeyId(UUID tenantKeyId) {
        this.tenantKeyId = tenantKeyId;
    }

    public Capacity tenantKey(TenantKey tenantKey) {

        this.tenantKey = tenantKey;
        return this;
    }

    /**
     * Get tenantKey
     * 
     * @return tenantKey
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_TENANT_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public TenantKey getTenantKey() {
        return tenantKey;
    }

    public void setTenantKey(TenantKey tenantKey) {
        this.tenantKey = tenantKey;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Capacity capacity = (Capacity) o;
        return Objects.equals(this.id, capacity.id) && Objects.equals(this.displayName, capacity.displayName)
                && Objects.equals(this.admins, capacity.admins) && Objects.equals(this.sku, capacity.sku)
                && Objects.equals(this.state, capacity.state)
                && Objects.equals(this.capacityUserAccessRight, capacity.capacityUserAccessRight)
                && Objects.equals(this.region, capacity.region)
                && Objects.equals(this.tenantKeyId, capacity.tenantKeyId)
                && Objects.equals(this.tenantKey, capacity.tenantKey);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, displayName, admins, sku, state, capacityUserAccessRight, region, tenantKeyId,
                tenantKey);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Capacity {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
        sb.append("    admins: ").append(toIndentedString(admins)).append("\n");
        sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
        sb.append("    state: ").append(toIndentedString(state)).append("\n");
        sb.append("    capacityUserAccessRight: ").append(toIndentedString(capacityUserAccessRight)).append("\n");
        sb.append("    region: ").append(toIndentedString(region)).append("\n");
        sb.append("    tenantKeyId: ").append(toIndentedString(tenantKeyId)).append("\n");
        sb.append("    tenantKey: ").append(toIndentedString(tenantKey)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
