/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.Objects;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Patch capacity request
 */
@ApiModel(description = "Patch capacity request")
@JsonPropertyOrder({ CapacityPatchRequest.JSON_PROPERTY_TENANT_KEY_ID })

public class CapacityPatchRequest {
    public static final String JSON_PROPERTY_TENANT_KEY_ID = "tenantKeyId";
    private UUID tenantKeyId;

    public CapacityPatchRequest tenantKeyId(UUID tenantKeyId) {

        this.tenantKeyId = tenantKeyId;
        return this;
    }

    /**
     * The id of the encryption key
     * 
     * @return tenantKeyId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The id of the encryption key")
    @JsonProperty(JSON_PROPERTY_TENANT_KEY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UUID getTenantKeyId() {
        return tenantKeyId;
    }

    public void setTenantKeyId(UUID tenantKeyId) {
        this.tenantKeyId = tenantKeyId;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CapacityPatchRequest capacityPatchRequest = (CapacityPatchRequest) o;
        return Objects.equals(this.tenantKeyId, capacityPatchRequest.tenantKeyId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(tenantKeyId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CapacityPatchRequest {\n");
        sb.append("    tenantKeyId: ").append(toIndentedString(tenantKeyId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
