/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A Power BI user access right entry for datasource
 */
@ApiModel(description = "A Power BI user access right entry for datasource")
@JsonPropertyOrder({ DatasourceUser.JSON_PROPERTY_DATASOURCE_ACCESS_RIGHT, DatasourceUser.JSON_PROPERTY_EMAIL_ADDRESS,
        DatasourceUser.JSON_PROPERTY_DISPLAY_NAME, DatasourceUser.JSON_PROPERTY_IDENTIFIER,
        DatasourceUser.JSON_PROPERTY_PRINCIPAL_TYPE })

public class DatasourceUser {
    /**
     * The user access rights for the datasource.
     */
    public enum DatasourceAccessRightEnum {
        NONE("None"),

        READ("Read"),

        READOVERRIDEEFFECTIVEIDENTITY("ReadOverrideEffectiveIdentity");

        private String value;

        DatasourceAccessRightEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static DatasourceAccessRightEnum fromValue(String value) {
            for (DatasourceAccessRightEnum b : DatasourceAccessRightEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_DATASOURCE_ACCESS_RIGHT = "datasourceAccessRight";
    private DatasourceAccessRightEnum datasourceAccessRight;

    public static final String JSON_PROPERTY_EMAIL_ADDRESS = "emailAddress";
    private String emailAddress;

    public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
    private String displayName;

    public static final String JSON_PROPERTY_IDENTIFIER = "identifier";
    private String identifier;

    /**
     * The principal type
     */
    public enum PrincipalTypeEnum {
        USER("User"),

        GROUP("Group"),

        APP("App");

        private String value;

        PrincipalTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static PrincipalTypeEnum fromValue(String value) {
            for (PrincipalTypeEnum b : PrincipalTypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_PRINCIPAL_TYPE = "principalType";
    private PrincipalTypeEnum principalType;

    public DatasourceUser datasourceAccessRight(DatasourceAccessRightEnum datasourceAccessRight) {

        this.datasourceAccessRight = datasourceAccessRight;
        return this;
    }

    /**
     * The user access rights for the datasource.
     * 
     * @return datasourceAccessRight
     **/
    @ApiModelProperty(required = true, value = "The user access rights for the datasource.")
    @JsonProperty(JSON_PROPERTY_DATASOURCE_ACCESS_RIGHT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public DatasourceAccessRightEnum getDatasourceAccessRight() {
        return datasourceAccessRight;
    }

    public void setDatasourceAccessRight(DatasourceAccessRightEnum datasourceAccessRight) {
        this.datasourceAccessRight = datasourceAccessRight;
    }

    public DatasourceUser emailAddress(String emailAddress) {

        this.emailAddress = emailAddress;
        return this;
    }

    /**
     * Email address of the user
     * 
     * @return emailAddress
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Email address of the user")
    @JsonProperty(JSON_PROPERTY_EMAIL_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getEmailAddress() {
        return emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    public DatasourceUser displayName(String displayName) {

        this.displayName = displayName;
        return this;
    }

    /**
     * Display name of the principal
     * 
     * @return displayName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Display name of the principal")
    @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public DatasourceUser identifier(String identifier) {

        this.identifier = identifier;
        return this;
    }

    /**
     * Identifier of the principal
     * 
     * @return identifier
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Identifier of the principal")
    @JsonProperty(JSON_PROPERTY_IDENTIFIER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getIdentifier() {
        return identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public DatasourceUser principalType(PrincipalTypeEnum principalType) {

        this.principalType = principalType;
        return this;
    }

    /**
     * The principal type
     * 
     * @return principalType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The principal type")
    @JsonProperty(JSON_PROPERTY_PRINCIPAL_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public PrincipalTypeEnum getPrincipalType() {
        return principalType;
    }

    public void setPrincipalType(PrincipalTypeEnum principalType) {
        this.principalType = principalType;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DatasourceUser datasourceUser = (DatasourceUser) o;
        return Objects.equals(this.datasourceAccessRight, datasourceUser.datasourceAccessRight)
                && Objects.equals(this.emailAddress, datasourceUser.emailAddress)
                && Objects.equals(this.displayName, datasourceUser.displayName)
                && Objects.equals(this.identifier, datasourceUser.identifier)
                && Objects.equals(this.principalType, datasourceUser.principalType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(datasourceAccessRight, emailAddress, displayName, identifier, principalType);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DatasourceUser {\n");
        sb.append("    datasourceAccessRight: ").append(toIndentedString(datasourceAccessRight)).append("\n");
        sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
        sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
        sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
        sb.append("    principalType: ").append(toIndentedString(principalType)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
