/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.Objects;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * The metadata of a dataflow
 */
@ApiModel(description = "The metadata of a dataflow")
@JsonPropertyOrder({ Dataflow.JSON_PROPERTY_OBJECT_ID, Dataflow.JSON_PROPERTY_NAME, Dataflow.JSON_PROPERTY_DESCRIPTION,
        Dataflow.JSON_PROPERTY_MODEL_URL, Dataflow.JSON_PROPERTY_CONFIGURED_BY })

public class Dataflow {
    public static final String JSON_PROPERTY_OBJECT_ID = "objectId";
    private UUID objectId;

    public static final String JSON_PROPERTY_NAME = "name";
    private String name;

    public static final String JSON_PROPERTY_DESCRIPTION = "description";
    private String description;

    public static final String JSON_PROPERTY_MODEL_URL = "modelUrl";
    private String modelUrl;

    public static final String JSON_PROPERTY_CONFIGURED_BY = "configuredBy";
    private String configuredBy;

    public Dataflow objectId(UUID objectId) {

        this.objectId = objectId;
        return this;
    }

    /**
     * The dataflow id
     * 
     * @return objectId
     **/
    @ApiModelProperty(required = true, value = "The dataflow id")
    @JsonProperty(JSON_PROPERTY_OBJECT_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public UUID getObjectId() {
        return objectId;
    }

    public void setObjectId(UUID objectId) {
        this.objectId = objectId;
    }

    public Dataflow name(String name) {

        this.name = name;
        return this;
    }

    /**
     * The dataflow name
     * 
     * @return name
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The dataflow name")
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Dataflow description(String description) {

        this.description = description;
        return this;
    }

    /**
     * The dataflow description
     * 
     * @return description
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The dataflow description")
    @JsonProperty(JSON_PROPERTY_DESCRIPTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Dataflow modelUrl(String modelUrl) {

        this.modelUrl = modelUrl;
        return this;
    }

    /**
     * A URL to the dataflow definition file (model.json)
     * 
     * @return modelUrl
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "A URL to the dataflow definition file (model.json)")
    @JsonProperty(JSON_PROPERTY_MODEL_URL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getModelUrl() {
        return modelUrl;
    }

    public void setModelUrl(String modelUrl) {
        this.modelUrl = modelUrl;
    }

    public Dataflow configuredBy(String configuredBy) {

        this.configuredBy = configuredBy;
        return this;
    }

    /**
     * The dataflow owner
     * 
     * @return configuredBy
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The dataflow owner")
    @JsonProperty(JSON_PROPERTY_CONFIGURED_BY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getConfiguredBy() {
        return configuredBy;
    }

    public void setConfiguredBy(String configuredBy) {
        this.configuredBy = configuredBy;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Dataflow dataflow = (Dataflow) o;
        return Objects.equals(this.objectId, dataflow.objectId) && Objects.equals(this.name, dataflow.name)
                && Objects.equals(this.description, dataflow.description)
                && Objects.equals(this.modelUrl, dataflow.modelUrl)
                && Objects.equals(this.configuredBy, dataflow.configuredBy);
    }

    @Override
    public int hashCode() {
        return Objects.hash(objectId, name, description, modelUrl, configuredBy);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Dataflow {\n");
        sb.append("    objectId: ").append(toIndentedString(objectId)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    modelUrl: ").append(toIndentedString(modelUrl)).append("\n");
        sb.append("    configuredBy: ").append(toIndentedString(configuredBy)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
