/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A Power BI Dependent dataflow
 */
@ApiModel(description = "A Power BI Dependent dataflow")
@JsonPropertyOrder({ DependentDataflow.JSON_PROPERTY_TARGET_DATAFLOW_ID, DependentDataflow.JSON_PROPERTY_GROUP_ID })

public class DependentDataflow {
    public static final String JSON_PROPERTY_TARGET_DATAFLOW_ID = "targetDataflowId";
    private String targetDataflowId;

    public static final String JSON_PROPERTY_GROUP_ID = "groupId";
    private String groupId;

    public DependentDataflow targetDataflowId(String targetDataflowId) {

        this.targetDataflowId = targetDataflowId;
        return this;
    }

    /**
     * The target dataflow id
     * 
     * @return targetDataflowId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The target dataflow id")
    @JsonProperty(JSON_PROPERTY_TARGET_DATAFLOW_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getTargetDataflowId() {
        return targetDataflowId;
    }

    public void setTargetDataflowId(String targetDataflowId) {
        this.targetDataflowId = targetDataflowId;
    }

    public DependentDataflow groupId(String groupId) {

        this.groupId = groupId;
        return this;
    }

    /**
     * The target group id
     * 
     * @return groupId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The target group id")
    @JsonProperty(JSON_PROPERTY_GROUP_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DependentDataflow dependentDataflow = (DependentDataflow) o;
        return Objects.equals(this.targetDataflowId, dependentDataflow.targetDataflowId)
                && Objects.equals(this.groupId, dependentDataflow.groupId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(targetDataflowId, groupId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DependentDataflow {\n");
        sb.append("    targetDataflowId: ").append(toIndentedString(targetDataflowId)).append("\n");
        sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
