/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Power BI refresh schedule request for DirectQuery or LiveConnection
 */
@ApiModel(description = "Power BI  refresh schedule request for DirectQuery or LiveConnection ")
@JsonPropertyOrder({ DirectQueryRefreshScheduleRequest.JSON_PROPERTY_VALUE })

public class DirectQueryRefreshScheduleRequest {
    public static final String JSON_PROPERTY_VALUE = "value";
    private DirectQueryRefreshSchedule value;

    public DirectQueryRefreshScheduleRequest value(DirectQueryRefreshSchedule value) {

        this.value = value;
        return this;
    }

    /**
     * Get value
     * 
     * @return value
     **/
    @ApiModelProperty(required = true, value = "")
    @JsonProperty(JSON_PROPERTY_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public DirectQueryRefreshSchedule getValue() {
        return value;
    }

    public void setValue(DirectQueryRefreshSchedule value) {
        this.value = value;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DirectQueryRefreshScheduleRequest directQueryRefreshScheduleRequest = (DirectQueryRefreshScheduleRequest) o;
        return Objects.equals(this.value, directQueryRefreshScheduleRequest.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DirectQueryRefreshScheduleRequest {\n");
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
