/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A single page configuration for the export request
 */
@ApiModel(description = "A single page configuration for the export request")
@JsonPropertyOrder({ ExportReportPage.JSON_PROPERTY_PAGE_NAME, ExportReportPage.JSON_PROPERTY_BOOKMARK })

public class ExportReportPage {
    public static final String JSON_PROPERTY_PAGE_NAME = "pageName";
    private String pageName;

    public static final String JSON_PROPERTY_BOOKMARK = "bookmark";
    private PageBookmark bookmark;

    public ExportReportPage pageName(String pageName) {

        this.pageName = pageName;
        return this;
    }

    /**
     * The page name
     * 
     * @return pageName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The page name")
    @JsonProperty(JSON_PROPERTY_PAGE_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPageName() {
        return pageName;
    }

    public void setPageName(String pageName) {
        this.pageName = pageName;
    }

    public ExportReportPage bookmark(PageBookmark bookmark) {

        this.bookmark = bookmark;
        return this;
    }

    /**
     * Get bookmark
     * 
     * @return bookmark
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_BOOKMARK)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public PageBookmark getBookmark() {
        return bookmark;
    }

    public void setBookmark(PageBookmark bookmark) {
        this.bookmark = bookmark;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExportReportPage exportReportPage = (ExportReportPage) o;
        return Objects.equals(this.pageName, exportReportPage.pageName)
                && Objects.equals(this.bookmark, exportReportPage.bookmark);
    }

    @Override
    public int hashCode() {
        return Objects.hash(pageName, bookmark);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ExportReportPage {\n");
        sb.append("    pageName: ").append(toIndentedString(pageName)).append("\n");
        sb.append("    bookmark: ").append(toIndentedString(bookmark)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
