/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * An object describing Export to file details and current state
 */
@ApiModel(description = "An object describing Export to file details and current state")
@JsonPropertyOrder({ Export.JSON_PROPERTY_ID, Export.JSON_PROPERTY_CREATED_DATE_TIME,
        Export.JSON_PROPERTY_LAST_ACTION_DATE_TIME, Export.JSON_PROPERTY_REPORT_ID, Export.JSON_PROPERTY_REPORT_NAME,
        Export.JSON_PROPERTY_STATUS, Export.JSON_PROPERTY_PERCENT_COMPLETE, Export.JSON_PROPERTY_RESOURCE_LOCATION,
        Export.JSON_PROPERTY_RESOURCE_FILE_EXTENSION, Export.JSON_PROPERTY_EXPIRATION_TIME })

public class Export {
    public static final String JSON_PROPERTY_ID = "id";
    private String id;

    public static final String JSON_PROPERTY_CREATED_DATE_TIME = "createdDateTime";
    private OffsetDateTime createdDateTime;

    public static final String JSON_PROPERTY_LAST_ACTION_DATE_TIME = "lastActionDateTime";
    private OffsetDateTime lastActionDateTime;

    public static final String JSON_PROPERTY_REPORT_ID = "reportId";
    private UUID reportId;

    public static final String JSON_PROPERTY_REPORT_NAME = "reportName";
    private String reportName;

    /**
     * The current state of the Export to file job
     */
    public enum StatusEnum {
        UNDEFINED("Undefined"),

        NOTSTARTED("NotStarted"),

        RUNNING("Running"),

        SUCCEEDED("Succeeded"),

        FAILED("Failed");

        private String value;

        StatusEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static StatusEnum fromValue(String value) {
            for (StatusEnum b : StatusEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_STATUS = "status";
    private StatusEnum status;

    public static final String JSON_PROPERTY_PERCENT_COMPLETE = "percentComplete";
    private Integer percentComplete;

    public static final String JSON_PROPERTY_RESOURCE_LOCATION = "resourceLocation";
    private String resourceLocation;

    public static final String JSON_PROPERTY_RESOURCE_FILE_EXTENSION = "ResourceFileExtension";
    private String resourceFileExtension;

    public static final String JSON_PROPERTY_EXPIRATION_TIME = "expirationTime";
    private OffsetDateTime expirationTime;

    public Export id(String id) {

        this.id = id;
        return this;
    }

    /**
     * The Export to file job ID
     * 
     * @return id
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The Export to file job ID")
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Export createdDateTime(OffsetDateTime createdDateTime) {

        this.createdDateTime = createdDateTime;
        return this;
    }

    /**
     * The start time of the Export to file job
     * 
     * @return createdDateTime
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The start time of the Export to file job")
    @JsonProperty(JSON_PROPERTY_CREATED_DATE_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getCreatedDateTime() {
        return createdDateTime;
    }

    public void setCreatedDateTime(OffsetDateTime createdDateTime) {
        this.createdDateTime = createdDateTime;
    }

    public Export lastActionDateTime(OffsetDateTime lastActionDateTime) {

        this.lastActionDateTime = lastActionDateTime;
        return this;
    }

    /**
     * The time of last change in the Export to file job
     * 
     * @return lastActionDateTime
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The time of last change in the Export to file job")
    @JsonProperty(JSON_PROPERTY_LAST_ACTION_DATE_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getLastActionDateTime() {
        return lastActionDateTime;
    }

    public void setLastActionDateTime(OffsetDateTime lastActionDateTime) {
        this.lastActionDateTime = lastActionDateTime;
    }

    public Export reportId(UUID reportId) {

        this.reportId = reportId;
        return this;
    }

    /**
     * The ID of the exported report
     * 
     * @return reportId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The ID of the exported report")
    @JsonProperty(JSON_PROPERTY_REPORT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UUID getReportId() {
        return reportId;
    }

    public void setReportId(UUID reportId) {
        this.reportId = reportId;
    }

    public Export reportName(String reportName) {

        this.reportName = reportName;
        return this;
    }

    /**
     * The name of the exported report
     * 
     * @return reportName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The name of the exported report")
    @JsonProperty(JSON_PROPERTY_REPORT_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getReportName() {
        return reportName;
    }

    public void setReportName(String reportName) {
        this.reportName = reportName;
    }

    public Export status(StatusEnum status) {

        this.status = status;
        return this;
    }

    /**
     * The current state of the Export to file job
     * 
     * @return status
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The current state of the Export to file job")
    @JsonProperty(JSON_PROPERTY_STATUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public StatusEnum getStatus() {
        return status;
    }

    public void setStatus(StatusEnum status) {
        this.status = status;
    }

    public Export percentComplete(Integer percentComplete) {

        this.percentComplete = percentComplete;
        return this;
    }

    /**
     * Indicate job progress as percentage minimum: 0 maximum: 100
     * 
     * @return percentComplete
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Indicate job progress as percentage")
    @JsonProperty(JSON_PROPERTY_PERCENT_COMPLETE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getPercentComplete() {
        return percentComplete;
    }

    public void setPercentComplete(Integer percentComplete) {
        this.percentComplete = percentComplete;
    }

    public Export resourceLocation(String resourceLocation) {

        this.resourceLocation = resourceLocation;
        return this;
    }

    /**
     * The URL for retrieving the exported file
     * 
     * @return resourceLocation
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The URL for retrieving the exported file")
    @JsonProperty(JSON_PROPERTY_RESOURCE_LOCATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getResourceLocation() {
        return resourceLocation;
    }

    public void setResourceLocation(String resourceLocation) {
        this.resourceLocation = resourceLocation;
    }

    public Export resourceFileExtension(String resourceFileExtension) {

        this.resourceFileExtension = resourceFileExtension;
        return this;
    }

    /**
     * The extension of the exported file
     * 
     * @return resourceFileExtension
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The extension of the exported file")
    @JsonProperty(JSON_PROPERTY_RESOURCE_FILE_EXTENSION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getResourceFileExtension() {
        return resourceFileExtension;
    }

    public void setResourceFileExtension(String resourceFileExtension) {
        this.resourceFileExtension = resourceFileExtension;
    }

    public Export expirationTime(OffsetDateTime expirationTime) {

        this.expirationTime = expirationTime;
        return this;
    }

    /**
     * The expiration time of the URL
     * 
     * @return expirationTime
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The expiration time of the URL")
    @JsonProperty(JSON_PROPERTY_EXPIRATION_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getExpirationTime() {
        return expirationTime;
    }

    public void setExpirationTime(OffsetDateTime expirationTime) {
        this.expirationTime = expirationTime;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Export export = (Export) o;
        return Objects.equals(this.id, export.id) && Objects.equals(this.createdDateTime, export.createdDateTime)
                && Objects.equals(this.lastActionDateTime, export.lastActionDateTime)
                && Objects.equals(this.reportId, export.reportId) && Objects.equals(this.reportName, export.reportName)
                && Objects.equals(this.status, export.status)
                && Objects.equals(this.percentComplete, export.percentComplete)
                && Objects.equals(this.resourceLocation, export.resourceLocation)
                && Objects.equals(this.resourceFileExtension, export.resourceFileExtension)
                && Objects.equals(this.expirationTime, export.expirationTime);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, createdDateTime, lastActionDateTime, reportId, reportName, status, percentComplete,
                resourceLocation, resourceFileExtension, expirationTime);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Export {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
        sb.append("    lastActionDateTime: ").append(toIndentedString(lastActionDateTime)).append("\n");
        sb.append("    reportId: ").append(toIndentedString(reportId)).append("\n");
        sb.append("    reportName: ").append(toIndentedString(reportName)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    percentComplete: ").append(toIndentedString(percentComplete)).append("\n");
        sb.append("    resourceLocation: ").append(toIndentedString(resourceLocation)).append("\n");
        sb.append("    resourceFileExtension: ").append(toIndentedString(resourceFileExtension)).append("\n");
        sb.append("    expirationTime: ").append(toIndentedString(expirationTime)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
