/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.Objects;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A Power BI gateway
 */
@ApiModel(description = "A Power BI gateway")
@JsonPropertyOrder({ Gateway.JSON_PROPERTY_ID, Gateway.JSON_PROPERTY_NAME, Gateway.JSON_PROPERTY_TYPE,
        Gateway.JSON_PROPERTY_GATEWAY_ANNOTATION, Gateway.JSON_PROPERTY_PUBLIC_KEY,
        Gateway.JSON_PROPERTY_GATEWAY_STATUS })

public class Gateway {
    public static final String JSON_PROPERTY_ID = "id";
    private UUID id;

    public static final String JSON_PROPERTY_NAME = "name";
    private String name;

    public static final String JSON_PROPERTY_TYPE = "type";
    private String type;

    public static final String JSON_PROPERTY_GATEWAY_ANNOTATION = "gatewayAnnotation";
    private String gatewayAnnotation;

    public static final String JSON_PROPERTY_PUBLIC_KEY = "publicKey";
    private GatewayPublicKey publicKey;

    public static final String JSON_PROPERTY_GATEWAY_STATUS = "gatewayStatus";
    private String gatewayStatus;

    public Gateway id(UUID id) {

        this.id = id;
        return this;
    }

    /**
     * The gateway id
     * 
     * @return id
     **/
    @ApiModelProperty(required = true, value = "The gateway id")
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public Gateway name(String name) {

        this.name = name;
        return this;
    }

    /**
     * The gateway name
     * 
     * @return name
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The gateway name")
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Gateway type(String type) {

        this.type = type;
        return this;
    }

    /**
     * The gateway type
     * 
     * @return type
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The gateway type")
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Gateway gatewayAnnotation(String gatewayAnnotation) {

        this.gatewayAnnotation = gatewayAnnotation;
        return this;
    }

    /**
     * Gateway metadata in json format
     * 
     * @return gatewayAnnotation
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Gateway metadata in json format")
    @JsonProperty(JSON_PROPERTY_GATEWAY_ANNOTATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getGatewayAnnotation() {
        return gatewayAnnotation;
    }

    public void setGatewayAnnotation(String gatewayAnnotation) {
        this.gatewayAnnotation = gatewayAnnotation;
    }

    public Gateway publicKey(GatewayPublicKey publicKey) {

        this.publicKey = publicKey;
        return this;
    }

    /**
     * Get publicKey
     * 
     * @return publicKey
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_PUBLIC_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public GatewayPublicKey getPublicKey() {
        return publicKey;
    }

    public void setPublicKey(GatewayPublicKey publicKey) {
        this.publicKey = publicKey;
    }

    public Gateway gatewayStatus(String gatewayStatus) {

        this.gatewayStatus = gatewayStatus;
        return this;
    }

    /**
     * The gateway connectivity status
     * 
     * @return gatewayStatus
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The gateway connectivity status")
    @JsonProperty(JSON_PROPERTY_GATEWAY_STATUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getGatewayStatus() {
        return gatewayStatus;
    }

    public void setGatewayStatus(String gatewayStatus) {
        this.gatewayStatus = gatewayStatus;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Gateway gateway = (Gateway) o;
        return Objects.equals(this.id, gateway.id) && Objects.equals(this.name, gateway.name)
                && Objects.equals(this.type, gateway.type)
                && Objects.equals(this.gatewayAnnotation, gateway.gatewayAnnotation)
                && Objects.equals(this.publicKey, gateway.publicKey)
                && Objects.equals(this.gatewayStatus, gateway.gatewayStatus);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, type, gatewayAnnotation, publicKey, gatewayStatus);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Gateway {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    gatewayAnnotation: ").append(toIndentedString(gatewayAnnotation)).append("\n");
        sb.append("    publicKey: ").append(toIndentedString(publicKey)).append("\n");
        sb.append("    gatewayStatus: ").append(toIndentedString(gatewayStatus)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
