/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.Objects;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * The workspace object for Generate Token Request V2.
 */
@ApiModel(description = "The workspace object for Generate Token Request V2.")
@JsonPropertyOrder({ GenerateTokenRequestV2TargetWorkspace.JSON_PROPERTY_ID })

public class GenerateTokenRequestV2TargetWorkspace {
    public static final String JSON_PROPERTY_ID = "id";
    private UUID id;

    public GenerateTokenRequestV2TargetWorkspace id(UUID id) {

        this.id = id;
        return this;
    }

    /**
     * Workspace Id
     * 
     * @return id
     **/
    @ApiModelProperty(required = true, value = "Workspace Id")
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GenerateTokenRequestV2TargetWorkspace generateTokenRequestV2TargetWorkspace = (GenerateTokenRequestV2TargetWorkspace) o;
        return Objects.equals(this.id, generateTokenRequestV2TargetWorkspace.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GenerateTokenRequestV2TargetWorkspace {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
