/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Power BI Generate Token Request V2
 */
@ApiModel(description = "Power BI Generate Token Request V2")
@JsonPropertyOrder({ GenerateTokenRequestV2.JSON_PROPERTY_DATASETS, GenerateTokenRequestV2.JSON_PROPERTY_REPORTS,
        GenerateTokenRequestV2.JSON_PROPERTY_TARGET_WORKSPACES, GenerateTokenRequestV2.JSON_PROPERTY_IDENTITIES })

public class GenerateTokenRequestV2 {
    public static final String JSON_PROPERTY_DATASETS = "datasets";
    private List<GenerateTokenRequestV2Dataset> datasets = null;

    public static final String JSON_PROPERTY_REPORTS = "reports";
    private List<GenerateTokenRequestV2Report> reports = null;

    public static final String JSON_PROPERTY_TARGET_WORKSPACES = "targetWorkspaces";
    private List<GenerateTokenRequestV2TargetWorkspace> targetWorkspaces = null;

    public static final String JSON_PROPERTY_IDENTITIES = "identities";
    private List<EffectiveIdentity> identities = null;

    public GenerateTokenRequestV2 datasets(List<GenerateTokenRequestV2Dataset> datasets) {

        this.datasets = datasets;
        return this;
    }

    public GenerateTokenRequestV2 addDatasetsItem(GenerateTokenRequestV2Dataset datasetsItem) {
        if (this.datasets == null) {
            this.datasets = new ArrayList<>();
        }
        this.datasets.add(datasetsItem);
        return this;
    }

    /**
     * List of datasets
     * 
     * @return datasets
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "List of datasets")
    @JsonProperty(JSON_PROPERTY_DATASETS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<GenerateTokenRequestV2Dataset> getDatasets() {
        return datasets;
    }

    public void setDatasets(List<GenerateTokenRequestV2Dataset> datasets) {
        this.datasets = datasets;
    }

    public GenerateTokenRequestV2 reports(List<GenerateTokenRequestV2Report> reports) {

        this.reports = reports;
        return this;
    }

    public GenerateTokenRequestV2 addReportsItem(GenerateTokenRequestV2Report reportsItem) {
        if (this.reports == null) {
            this.reports = new ArrayList<>();
        }
        this.reports.add(reportsItem);
        return this;
    }

    /**
     * List of reports
     * 
     * @return reports
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "List of reports")
    @JsonProperty(JSON_PROPERTY_REPORTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<GenerateTokenRequestV2Report> getReports() {
        return reports;
    }

    public void setReports(List<GenerateTokenRequestV2Report> reports) {
        this.reports = reports;
    }

    public GenerateTokenRequestV2 targetWorkspaces(List<GenerateTokenRequestV2TargetWorkspace> targetWorkspaces) {

        this.targetWorkspaces = targetWorkspaces;
        return this;
    }

    public GenerateTokenRequestV2 addTargetWorkspacesItem(GenerateTokenRequestV2TargetWorkspace targetWorkspacesItem) {
        if (this.targetWorkspaces == null) {
            this.targetWorkspaces = new ArrayList<>();
        }
        this.targetWorkspaces.add(targetWorkspacesItem);
        return this;
    }

    /**
     * List of target workspaces
     * 
     * @return targetWorkspaces
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "List of target workspaces")
    @JsonProperty(JSON_PROPERTY_TARGET_WORKSPACES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<GenerateTokenRequestV2TargetWorkspace> getTargetWorkspaces() {
        return targetWorkspaces;
    }

    public void setTargetWorkspaces(List<GenerateTokenRequestV2TargetWorkspace> targetWorkspaces) {
        this.targetWorkspaces = targetWorkspaces;
    }

    public GenerateTokenRequestV2 identities(List<EffectiveIdentity> identities) {

        this.identities = identities;
        return this;
    }

    public GenerateTokenRequestV2 addIdentitiesItem(EffectiveIdentity identitiesItem) {
        if (this.identities == null) {
            this.identities = new ArrayList<>();
        }
        this.identities.add(identitiesItem);
        return this;
    }

    /**
     * List of identities to use for RLS rules.
     * 
     * @return identities
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "List of identities to use for RLS rules.")
    @JsonProperty(JSON_PROPERTY_IDENTITIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<EffectiveIdentity> getIdentities() {
        return identities;
    }

    public void setIdentities(List<EffectiveIdentity> identities) {
        this.identities = identities;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GenerateTokenRequestV2 generateTokenRequestV2 = (GenerateTokenRequestV2) o;
        return Objects.equals(this.datasets, generateTokenRequestV2.datasets)
                && Objects.equals(this.reports, generateTokenRequestV2.reports)
                && Objects.equals(this.targetWorkspaces, generateTokenRequestV2.targetWorkspaces)
                && Objects.equals(this.identities, generateTokenRequestV2.identities);
    }

    @Override
    public int hashCode() {
        return Objects.hash(datasets, reports, targetWorkspaces, identities);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GenerateTokenRequestV2 {\n");
        sb.append("    datasets: ").append(toIndentedString(datasets)).append("\n");
        sb.append("    reports: ").append(toIndentedString(reports)).append("\n");
        sb.append("    targetWorkspaces: ").append(toIndentedString(targetWorkspaces)).append("\n");
        sb.append("    identities: ").append(toIndentedString(identities)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
