/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Power BI Generate Token Request
 */
@ApiModel(description = "Power BI Generate Token Request")
@JsonPropertyOrder({ GenerateTokenRequest.JSON_PROPERTY_ACCESS_LEVEL, GenerateTokenRequest.JSON_PROPERTY_DATASET_ID,
        GenerateTokenRequest.JSON_PROPERTY_ALLOW_SAVE_AS, GenerateTokenRequest.JSON_PROPERTY_IDENTITIES })

public class GenerateTokenRequest {
    /**
     * Required access level for EmbedToken generation
     */
    public enum AccessLevelEnum {
        VIEW("View"),

        EDIT("Edit"),

        CREATE("Create");

        private String value;

        AccessLevelEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static AccessLevelEnum fromValue(String value) {
            for (AccessLevelEnum b : AccessLevelEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_ACCESS_LEVEL = "accessLevel";
    private AccessLevelEnum accessLevel;

    public static final String JSON_PROPERTY_DATASET_ID = "datasetId";
    private String datasetId;

    public static final String JSON_PROPERTY_ALLOW_SAVE_AS = "allowSaveAs";
    private Boolean allowSaveAs;

    public static final String JSON_PROPERTY_IDENTITIES = "identities";
    private List<EffectiveIdentity> identities = null;

    public GenerateTokenRequest accessLevel(AccessLevelEnum accessLevel) {

        this.accessLevel = accessLevel;
        return this;
    }

    /**
     * Required access level for EmbedToken generation
     * 
     * @return accessLevel
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Required access level for EmbedToken generation")
    @JsonProperty(JSON_PROPERTY_ACCESS_LEVEL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public AccessLevelEnum getAccessLevel() {
        return accessLevel;
    }

    public void setAccessLevel(AccessLevelEnum accessLevel) {
        this.accessLevel = accessLevel;
    }

    public GenerateTokenRequest datasetId(String datasetId) {

        this.datasetId = datasetId;
        return this;
    }

    /**
     * Dataset id for report creation. Only applies when generating EmbedToken for
     * report creation.
     * 
     * @return datasetId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Dataset id for report creation. Only applies when generating EmbedToken for report creation.")
    @JsonProperty(JSON_PROPERTY_DATASET_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDatasetId() {
        return datasetId;
    }

    public void setDatasetId(String datasetId) {
        this.datasetId = datasetId;
    }

    public GenerateTokenRequest allowSaveAs(Boolean allowSaveAs) {

        this.allowSaveAs = allowSaveAs;
        return this;
    }

    /**
     * Indicates an embedded report can be saved as a new report. Default value is
     * &#39;false&#39;. Only applies when generating EmbedToken for report
     * embedding.
     * 
     * @return allowSaveAs
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Indicates an embedded report can be saved as a new report. Default value is 'false'. Only applies when generating EmbedToken for report embedding.")
    @JsonProperty(JSON_PROPERTY_ALLOW_SAVE_AS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getAllowSaveAs() {
        return allowSaveAs;
    }

    public void setAllowSaveAs(Boolean allowSaveAs) {
        this.allowSaveAs = allowSaveAs;
    }

    public GenerateTokenRequest identities(List<EffectiveIdentity> identities) {

        this.identities = identities;
        return this;
    }

    public GenerateTokenRequest addIdentitiesItem(EffectiveIdentity identitiesItem) {
        if (this.identities == null) {
            this.identities = new ArrayList<>();
        }
        this.identities.add(identitiesItem);
        return this;
    }

    /**
     * List of identities to use for RLS rules.
     * 
     * @return identities
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "List of identities to use for RLS rules.")
    @JsonProperty(JSON_PROPERTY_IDENTITIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<EffectiveIdentity> getIdentities() {
        return identities;
    }

    public void setIdentities(List<EffectiveIdentity> identities) {
        this.identities = identities;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GenerateTokenRequest generateTokenRequest = (GenerateTokenRequest) o;
        return Objects.equals(this.accessLevel, generateTokenRequest.accessLevel)
                && Objects.equals(this.datasetId, generateTokenRequest.datasetId)
                && Objects.equals(this.allowSaveAs, generateTokenRequest.allowSaveAs)
                && Objects.equals(this.identities, generateTokenRequest.identities);
    }

    @Override
    public int hashCode() {
        return Objects.hash(accessLevel, datasetId, allowSaveAs, identities);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GenerateTokenRequest {\n");
        sb.append("    accessLevel: ").append(toIndentedString(accessLevel)).append("\n");
        sb.append("    datasetId: ").append(toIndentedString(datasetId)).append("\n");
        sb.append("    allowSaveAs: ").append(toIndentedString(allowSaveAs)).append("\n");
        sb.append("    identities: ").append(toIndentedString(identities)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
