/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Power BI dataset parameter
 */
@ApiModel(description = "Power BI dataset parameter")
@JsonPropertyOrder({ MashupParameter.JSON_PROPERTY_NAME, MashupParameter.JSON_PROPERTY_TYPE,
        MashupParameter.JSON_PROPERTY_CURRENT_VALUE, MashupParameter.JSON_PROPERTY_IS_REQUIRED })

public class MashupParameter {
    public static final String JSON_PROPERTY_NAME = "name";
    private String name;

    public static final String JSON_PROPERTY_TYPE = "type";
    private String type;

    public static final String JSON_PROPERTY_CURRENT_VALUE = "currentValue";
    private String currentValue;

    public static final String JSON_PROPERTY_IS_REQUIRED = "isRequired";
    private Boolean isRequired;

    public MashupParameter name(String name) {

        this.name = name;
        return this;
    }

    /**
     * The parameter name
     * 
     * @return name
     **/
    @ApiModelProperty(required = true, value = "The parameter name")
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public MashupParameter type(String type) {

        this.type = type;
        return this;
    }

    /**
     * The parameter type
     * 
     * @return type
     **/
    @ApiModelProperty(required = true, value = "The parameter type")
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public MashupParameter currentValue(String currentValue) {

        this.currentValue = currentValue;
        return this;
    }

    /**
     * The parameter current value
     * 
     * @return currentValue
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The parameter current value")
    @JsonProperty(JSON_PROPERTY_CURRENT_VALUE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getCurrentValue() {
        return currentValue;
    }

    public void setCurrentValue(String currentValue) {
        this.currentValue = currentValue;
    }

    public MashupParameter isRequired(Boolean isRequired) {

        this.isRequired = isRequired;
        return this;
    }

    /**
     * Is dataset parameter required
     * 
     * @return isRequired
     **/
    @ApiModelProperty(required = true, value = "Is dataset parameter required")
    @JsonProperty(JSON_PROPERTY_IS_REQUIRED)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public Boolean getIsRequired() {
        return isRequired;
    }

    public void setIsRequired(Boolean isRequired) {
        this.isRequired = isRequired;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MashupParameter mashupParameter = (MashupParameter) o;
        return Objects.equals(this.name, mashupParameter.name) && Objects.equals(this.type, mashupParameter.type)
                && Objects.equals(this.currentValue, mashupParameter.currentValue)
                && Objects.equals(this.isRequired, mashupParameter.isRequired);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, type, currentValue, isRequired);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MashupParameter {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    currentValue: ").append(toIndentedString(currentValue)).append("\n");
        sb.append("    isRequired: ").append(toIndentedString(isRequired)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
