/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Paginated report Export to file configuration
 */
@ApiModel(description = "Paginated report Export to file configuration")
@JsonPropertyOrder({ PaginatedReportExportConfiguration.JSON_PROPERTY_IDENTITIES,
        PaginatedReportExportConfiguration.JSON_PROPERTY_FORMAT_SETTINGS,
        PaginatedReportExportConfiguration.JSON_PROPERTY_PARAMETER_VALUES })

public class PaginatedReportExportConfiguration {
    public static final String JSON_PROPERTY_IDENTITIES = "identities";
    private List<EffectiveIdentity> identities = null;

    public static final String JSON_PROPERTY_FORMAT_SETTINGS = "formatSettings";
    private Map<String, String> formatSettings = null;

    public static final String JSON_PROPERTY_PARAMETER_VALUES = "parameterValues";
    private List<ParameterValue> parameterValues = null;

    public PaginatedReportExportConfiguration identities(List<EffectiveIdentity> identities) {

        this.identities = identities;
        return this;
    }

    public PaginatedReportExportConfiguration addIdentitiesItem(EffectiveIdentity identitiesItem) {
        if (this.identities == null) {
            this.identities = new ArrayList<>();
        }
        this.identities.add(identitiesItem);
        return this;
    }

    /**
     * List of identities to use for RLS rules
     * 
     * @return identities
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "List of identities to use for RLS rules")
    @JsonProperty(JSON_PROPERTY_IDENTITIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<EffectiveIdentity> getIdentities() {
        return identities;
    }

    public void setIdentities(List<EffectiveIdentity> identities) {
        this.identities = identities;
    }

    public PaginatedReportExportConfiguration formatSettings(Map<String, String> formatSettings) {

        this.formatSettings = formatSettings;
        return this;
    }

    public PaginatedReportExportConfiguration putFormatSettingsItem(String key, String formatSettingsItem) {
        if (this.formatSettings == null) {
            this.formatSettings = new HashMap<>();
        }
        this.formatSettings.put(key, formatSettingsItem);
        return this;
    }

    /**
     * Dictionary of format settings. The keys are the device info property names
     * for the requested file format.
     * 
     * @return formatSettings
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Dictionary of format settings. The keys are the device info property names for the requested file format.")
    @JsonProperty(JSON_PROPERTY_FORMAT_SETTINGS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Map<String, String> getFormatSettings() {
        return formatSettings;
    }

    public void setFormatSettings(Map<String, String> formatSettings) {
        this.formatSettings = formatSettings;
    }

    public PaginatedReportExportConfiguration parameterValues(List<ParameterValue> parameterValues) {

        this.parameterValues = parameterValues;
        return this;
    }

    public PaginatedReportExportConfiguration addParameterValuesItem(ParameterValue parameterValuesItem) {
        if (this.parameterValues == null) {
            this.parameterValues = new ArrayList<>();
        }
        this.parameterValues.add(parameterValuesItem);
        return this;
    }

    /**
     * List of report parameters
     * 
     * @return parameterValues
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "List of report parameters")
    @JsonProperty(JSON_PROPERTY_PARAMETER_VALUES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<ParameterValue> getParameterValues() {
        return parameterValues;
    }

    public void setParameterValues(List<ParameterValue> parameterValues) {
        this.parameterValues = parameterValues;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PaginatedReportExportConfiguration paginatedReportExportConfiguration = (PaginatedReportExportConfiguration) o;
        return Objects.equals(this.identities, paginatedReportExportConfiguration.identities)
                && Objects.equals(this.formatSettings, paginatedReportExportConfiguration.formatSettings)
                && Objects.equals(this.parameterValues, paginatedReportExportConfiguration.parameterValues);
    }

    @Override
    public int hashCode() {
        return Objects.hash(identities, formatSettings, parameterValues);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PaginatedReportExportConfiguration {\n");
        sb.append("    identities: ").append(toIndentedString(identities)).append("\n");
        sb.append("    formatSettings: ").append(toIndentedString(formatSettings)).append("\n");
        sb.append("    parameterValues: ").append(toIndentedString(parameterValues)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
