/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A publish datasource to gateway request
 */
@ApiModel(description = "A publish datasource to gateway request")
@JsonPropertyOrder({ PublishDatasourceToGatewayRequest.JSON_PROPERTY_DATA_SOURCE_TYPE,
        PublishDatasourceToGatewayRequest.JSON_PROPERTY_CONNECTION_DETAILS,
        PublishDatasourceToGatewayRequest.JSON_PROPERTY_CREDENTIAL_DETAILS,
        PublishDatasourceToGatewayRequest.JSON_PROPERTY_DATA_SOURCE_NAME })

public class PublishDatasourceToGatewayRequest {
    public static final String JSON_PROPERTY_DATA_SOURCE_TYPE = "dataSourceType";
    private String dataSourceType;

    public static final String JSON_PROPERTY_CONNECTION_DETAILS = "connectionDetails";
    private String connectionDetails;

    public static final String JSON_PROPERTY_CREDENTIAL_DETAILS = "credentialDetails";
    private CredentialDetails credentialDetails;

    public static final String JSON_PROPERTY_DATA_SOURCE_NAME = "dataSourceName";
    private String dataSourceName;

    public PublishDatasourceToGatewayRequest dataSourceType(String dataSourceType) {

        this.dataSourceType = dataSourceType;
        return this;
    }

    /**
     * The datasource type
     * 
     * @return dataSourceType
     **/
    @ApiModelProperty(required = true, value = "The datasource type")
    @JsonProperty(JSON_PROPERTY_DATA_SOURCE_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getDataSourceType() {
        return dataSourceType;
    }

    public void setDataSourceType(String dataSourceType) {
        this.dataSourceType = dataSourceType;
    }

    public PublishDatasourceToGatewayRequest connectionDetails(String connectionDetails) {

        this.connectionDetails = connectionDetails;
        return this;
    }

    /**
     * The connection details
     * 
     * @return connectionDetails
     **/
    @ApiModelProperty(required = true, value = "The connection details")
    @JsonProperty(JSON_PROPERTY_CONNECTION_DETAILS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getConnectionDetails() {
        return connectionDetails;
    }

    public void setConnectionDetails(String connectionDetails) {
        this.connectionDetails = connectionDetails;
    }

    public PublishDatasourceToGatewayRequest credentialDetails(CredentialDetails credentialDetails) {

        this.credentialDetails = credentialDetails;
        return this;
    }

    /**
     * Get credentialDetails
     * 
     * @return credentialDetails
     **/
    @ApiModelProperty(required = true, value = "")
    @JsonProperty(JSON_PROPERTY_CREDENTIAL_DETAILS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public CredentialDetails getCredentialDetails() {
        return credentialDetails;
    }

    public void setCredentialDetails(CredentialDetails credentialDetails) {
        this.credentialDetails = credentialDetails;
    }

    public PublishDatasourceToGatewayRequest dataSourceName(String dataSourceName) {

        this.dataSourceName = dataSourceName;
        return this;
    }

    /**
     * The datasource name
     * 
     * @return dataSourceName
     **/
    @ApiModelProperty(required = true, value = "The datasource name")
    @JsonProperty(JSON_PROPERTY_DATA_SOURCE_NAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getDataSourceName() {
        return dataSourceName;
    }

    public void setDataSourceName(String dataSourceName) {
        this.dataSourceName = dataSourceName;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PublishDatasourceToGatewayRequest publishDatasourceToGatewayRequest = (PublishDatasourceToGatewayRequest) o;
        return Objects.equals(this.dataSourceType, publishDatasourceToGatewayRequest.dataSourceType)
                && Objects.equals(this.connectionDetails, publishDatasourceToGatewayRequest.connectionDetails)
                && Objects.equals(this.credentialDetails, publishDatasourceToGatewayRequest.credentialDetails)
                && Objects.equals(this.dataSourceName, publishDatasourceToGatewayRequest.dataSourceName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(dataSourceType, connectionDetails, credentialDetails, dataSourceName);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PublishDatasourceToGatewayRequest {\n");
        sb.append("    dataSourceType: ").append(toIndentedString(dataSourceType)).append("\n");
        sb.append("    connectionDetails: ").append(toIndentedString(connectionDetails)).append("\n");
        sb.append("    credentialDetails: ").append(toIndentedString(credentialDetails)).append("\n");
        sb.append("    dataSourceName: ").append(toIndentedString(dataSourceName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
