/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.Objects;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Source from existing report
 */
@ApiModel(description = "Source from existing report")
@JsonPropertyOrder({ SourceReport.JSON_PROPERTY_SOURCE_REPORT_ID, SourceReport.JSON_PROPERTY_SOURCE_WORKSPACE_ID })

public class SourceReport {
    public static final String JSON_PROPERTY_SOURCE_REPORT_ID = "sourceReportId";
    private UUID sourceReportId;

    public static final String JSON_PROPERTY_SOURCE_WORKSPACE_ID = "sourceWorkspaceId";
    private UUID sourceWorkspaceId;

    public SourceReport sourceReportId(UUID sourceReportId) {

        this.sourceReportId = sourceReportId;
        return this;
    }

    /**
     * source report id
     * 
     * @return sourceReportId
     **/
    @ApiModelProperty(required = true, value = "source report id")
    @JsonProperty(JSON_PROPERTY_SOURCE_REPORT_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public UUID getSourceReportId() {
        return sourceReportId;
    }

    public void setSourceReportId(UUID sourceReportId) {
        this.sourceReportId = sourceReportId;
    }

    public SourceReport sourceWorkspaceId(UUID sourceWorkspaceId) {

        this.sourceWorkspaceId = sourceWorkspaceId;
        return this;
    }

    /**
     * source worksapce id
     * 
     * @return sourceWorkspaceId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "source worksapce id")
    @JsonProperty(JSON_PROPERTY_SOURCE_WORKSPACE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UUID getSourceWorkspaceId() {
        return sourceWorkspaceId;
    }

    public void setSourceWorkspaceId(UUID sourceWorkspaceId) {
        this.sourceWorkspaceId = sourceWorkspaceId;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SourceReport sourceReport = (SourceReport) o;
        return Objects.equals(this.sourceReportId, sourceReport.sourceReportId)
                && Objects.equals(this.sourceWorkspaceId, sourceReport.sourceWorkspaceId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(sourceReportId, sourceWorkspaceId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SourceReport {\n");
        sb.append("    sourceReportId: ").append(toIndentedString(sourceReportId)).append("\n");
        sb.append("    sourceWorkspaceId: ").append(toIndentedString(sourceWorkspaceId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
