/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.time.OffsetDateTime;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Power BI update report content request
 */
@ApiModel(description = "Power BI update report content request")
@JsonPropertyOrder({ TemporaryUploadLocation.JSON_PROPERTY_URL, TemporaryUploadLocation.JSON_PROPERTY_EXPIRATION_TIME })

public class TemporaryUploadLocation {
    public static final String JSON_PROPERTY_URL = "Url";
    private String url;

    public static final String JSON_PROPERTY_EXPIRATION_TIME = "ExpirationTime";
    private OffsetDateTime expirationTime;

    public TemporaryUploadLocation url(String url) {

        this.url = url;
        return this;
    }

    /**
     * The shared access signature (SAS) url for the temporary blob storage
     * 
     * @return url
     **/
    @ApiModelProperty(required = true, value = "The shared access signature (SAS) url for the temporary blob storage")
    @JsonProperty(JSON_PROPERTY_URL)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public TemporaryUploadLocation expirationTime(OffsetDateTime expirationTime) {

        this.expirationTime = expirationTime;
        return this;
    }

    /**
     * The expiration time of the shared access signature (SAS) url
     * 
     * @return expirationTime
     **/
    @ApiModelProperty(required = true, value = "The expiration time of the shared access signature (SAS) url")
    @JsonProperty(JSON_PROPERTY_EXPIRATION_TIME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public OffsetDateTime getExpirationTime() {
        return expirationTime;
    }

    public void setExpirationTime(OffsetDateTime expirationTime) {
        this.expirationTime = expirationTime;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TemporaryUploadLocation temporaryUploadLocation = (TemporaryUploadLocation) o;
        return Objects.equals(this.url, temporaryUploadLocation.url)
                && Objects.equals(this.expirationTime, temporaryUploadLocation.expirationTime);
    }

    @Override
    public int hashCode() {
        return Objects.hash(url, expirationTime);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TemporaryUploadLocation {\n");
        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("    expirationTime: ").append(toIndentedString(expirationTime)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
