/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Encryption key information
 */
@ApiModel(description = "Encryption key information")
@JsonPropertyOrder({ TenantKey.JSON_PROPERTY_ID, TenantKey.JSON_PROPERTY_NAME,
        TenantKey.JSON_PROPERTY_KEY_VAULT_KEY_IDENTIFIER, TenantKey.JSON_PROPERTY_IS_DEFAULT,
        TenantKey.JSON_PROPERTY_CREATED_AT, TenantKey.JSON_PROPERTY_UPDATED_AT })

public class TenantKey {
    public static final String JSON_PROPERTY_ID = "id";
    private UUID id;

    public static final String JSON_PROPERTY_NAME = "name";
    private String name;

    public static final String JSON_PROPERTY_KEY_VAULT_KEY_IDENTIFIER = "keyVaultKeyIdentifier";
    private String keyVaultKeyIdentifier;

    public static final String JSON_PROPERTY_IS_DEFAULT = "isDefault";
    private Boolean isDefault;

    public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
    private OffsetDateTime createdAt;

    public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
    private OffsetDateTime updatedAt;

    public TenantKey id(UUID id) {

        this.id = id;
        return this;
    }

    /**
     * The id of the encryption key
     * 
     * @return id
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The id of the encryption key")
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public TenantKey name(String name) {

        this.name = name;
        return this;
    }

    /**
     * The name of the encryption key
     * 
     * @return name
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The name of the encryption key")
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public TenantKey keyVaultKeyIdentifier(String keyVaultKeyIdentifier) {

        this.keyVaultKeyIdentifier = keyVaultKeyIdentifier;
        return this;
    }

    /**
     * Uri to the version of the Azure Key Vault key
     * 
     * @return keyVaultKeyIdentifier
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Uri to the version of the Azure Key Vault key")
    @JsonProperty(JSON_PROPERTY_KEY_VAULT_KEY_IDENTIFIER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getKeyVaultKeyIdentifier() {
        return keyVaultKeyIdentifier;
    }

    public void setKeyVaultKeyIdentifier(String keyVaultKeyIdentifier) {
        this.keyVaultKeyIdentifier = keyVaultKeyIdentifier;
    }

    public TenantKey isDefault(Boolean isDefault) {

        this.isDefault = isDefault;
        return this;
    }

    /**
     * Indicates that this key is set as default for the entire tenant. Any new
     * capacity creation will inherit this key upon creation
     * 
     * @return isDefault
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Indicates that this key is set as default for the entire tenant. Any new capacity creation will inherit this key upon creation")
    @JsonProperty(JSON_PROPERTY_IS_DEFAULT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getIsDefault() {
        return isDefault;
    }

    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    public TenantKey createdAt(OffsetDateTime createdAt) {

        this.createdAt = createdAt;
        return this;
    }

    /**
     * Encryption key creation time
     * 
     * @return createdAt
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Encryption key creation time")
    @JsonProperty(JSON_PROPERTY_CREATED_AT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public TenantKey updatedAt(OffsetDateTime updatedAt) {

        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Encryption key last update time
     * 
     * @return updatedAt
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Encryption key last update time")
    @JsonProperty(JSON_PROPERTY_UPDATED_AT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TenantKey tenantKey = (TenantKey) o;
        return Objects.equals(this.id, tenantKey.id) && Objects.equals(this.name, tenantKey.name)
                && Objects.equals(this.keyVaultKeyIdentifier, tenantKey.keyVaultKeyIdentifier)
                && Objects.equals(this.isDefault, tenantKey.isDefault)
                && Objects.equals(this.createdAt, tenantKey.createdAt)
                && Objects.equals(this.updatedAt, tenantKey.updatedAt);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, keyVaultKeyIdentifier, isDefault, createdAt, updatedAt);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TenantKey {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    keyVaultKeyIdentifier: ").append(toIndentedString(keyVaultKeyIdentifier)).append("\n");
        sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
        sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
        sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
