/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Rotate encryption key request
 */
@ApiModel(description = "Rotate encryption key request")
@JsonPropertyOrder({ TenantKeyRotationRequest.JSON_PROPERTY_KEY_VAULT_KEY_IDENTIFIER })

public class TenantKeyRotationRequest {
    public static final String JSON_PROPERTY_KEY_VAULT_KEY_IDENTIFIER = "keyVaultKeyIdentifier";
    private String keyVaultKeyIdentifier;

    public TenantKeyRotationRequest keyVaultKeyIdentifier(String keyVaultKeyIdentifier) {

        this.keyVaultKeyIdentifier = keyVaultKeyIdentifier;
        return this;
    }

    /**
     * Uri to the version of the Azure Key Vault key to be used
     * 
     * @return keyVaultKeyIdentifier
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Uri to the version of the Azure Key Vault key to be used")
    @JsonProperty(JSON_PROPERTY_KEY_VAULT_KEY_IDENTIFIER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getKeyVaultKeyIdentifier() {
        return keyVaultKeyIdentifier;
    }

    public void setKeyVaultKeyIdentifier(String keyVaultKeyIdentifier) {
        this.keyVaultKeyIdentifier = keyVaultKeyIdentifier;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TenantKeyRotationRequest tenantKeyRotationRequest = (TenantKeyRotationRequest) o;
        return Objects.equals(this.keyVaultKeyIdentifier, tenantKeyRotationRequest.keyVaultKeyIdentifier);
    }

    @Override
    public int hashCode() {
        return Objects.hash(keyVaultKeyIdentifier);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TenantKeyRotationRequest {\n");
        sb.append("    keyVaultKeyIdentifier: ").append(toIndentedString(keyVaultKeyIdentifier)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
