/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Request body for migrating workspaces to shared capacity as tenant admin
 */
@ApiModel(description = "Request body for migrating workspaces to shared capacity as tenant admin")
@JsonPropertyOrder({ UnassignWorkspacesCapacityRequest.JSON_PROPERTY_WORKSPACES_TO_UNASSIGN })

public class UnassignWorkspacesCapacityRequest {
    public static final String JSON_PROPERTY_WORKSPACES_TO_UNASSIGN = "workspacesToUnassign";
    private List<String> workspacesToUnassign = new ArrayList<>();

    public UnassignWorkspacesCapacityRequest workspacesToUnassign(List<String> workspacesToUnassign) {

        this.workspacesToUnassign = workspacesToUnassign;
        return this;
    }

    public UnassignWorkspacesCapacityRequest addWorkspacesToUnassignItem(String workspacesToUnassignItem) {
        this.workspacesToUnassign.add(workspacesToUnassignItem);
        return this;
    }

    /**
     * Workspaces to be migrated to shared capacity
     * 
     * @return workspacesToUnassign
     **/
    @ApiModelProperty(required = true, value = "Workspaces to be migrated to shared capacity")
    @JsonProperty(JSON_PROPERTY_WORKSPACES_TO_UNASSIGN)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public List<String> getWorkspacesToUnassign() {
        return workspacesToUnassign;
    }

    public void setWorkspacesToUnassign(List<String> workspacesToUnassign) {
        this.workspacesToUnassign = workspacesToUnassign;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UnassignWorkspacesCapacityRequest unassignWorkspacesCapacityRequest = (UnassignWorkspacesCapacityRequest) o;
        return Objects.equals(this.workspacesToUnassign, unassignWorkspacesCapacityRequest.workspacesToUnassign);
    }

    @Override
    public int hashCode() {
        return Objects.hash(workspacesToUnassign);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UnassignWorkspacesCapacityRequest {\n");
        sb.append("    workspacesToUnassign: ").append(toIndentedString(workspacesToUnassign)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
