/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Power BI dataset parameter update details
 */
@ApiModel(description = "Power BI dataset parameter update details")
@JsonPropertyOrder({ UpdateMashupParameterDetails.JSON_PROPERTY_NAME,
        UpdateMashupParameterDetails.JSON_PROPERTY_NEW_VALUE })

public class UpdateMashupParameterDetails {
    public static final String JSON_PROPERTY_NAME = "name";
    private String name;

    public static final String JSON_PROPERTY_NEW_VALUE = "newValue";
    private String newValue;

    public UpdateMashupParameterDetails name(String name) {

        this.name = name;
        return this;
    }

    /**
     * The parameter name
     * 
     * @return name
     **/
    @ApiModelProperty(required = true, value = "The parameter name")
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public UpdateMashupParameterDetails newValue(String newValue) {

        this.newValue = newValue;
        return this;
    }

    /**
     * The parameter new value
     * 
     * @return newValue
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The parameter new value")
    @JsonProperty(JSON_PROPERTY_NEW_VALUE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getNewValue() {
        return newValue;
    }

    public void setNewValue(String newValue) {
        this.newValue = newValue;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateMashupParameterDetails updateMashupParameterDetails = (UpdateMashupParameterDetails) o;
        return Objects.equals(this.name, updateMashupParameterDetails.name)
                && Objects.equals(this.newValue, updateMashupParameterDetails.newValue);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, newValue);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UpdateMashupParameterDetails {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    newValue: ").append(toIndentedString(newValue)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
