/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * An update datasource to gateway request
 */
@ApiModel(description = "An update datasource to gateway request")
@JsonPropertyOrder({ UpdateDatasourceRequest.JSON_PROPERTY_CREDENTIAL_DETAILS })

public class UpdateDatasourceRequest {
    public static final String JSON_PROPERTY_CREDENTIAL_DETAILS = "credentialDetails";
    private CredentialDetails credentialDetails;

    public UpdateDatasourceRequest credentialDetails(CredentialDetails credentialDetails) {

        this.credentialDetails = credentialDetails;
        return this;
    }

    /**
     * Get credentialDetails
     * 
     * @return credentialDetails
     **/
    @ApiModelProperty(required = true, value = "")
    @JsonProperty(JSON_PROPERTY_CREDENTIAL_DETAILS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public CredentialDetails getCredentialDetails() {
        return credentialDetails;
    }

    public void setCredentialDetails(CredentialDetails credentialDetails) {
        this.credentialDetails = credentialDetails;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateDatasourceRequest updateDatasourceRequest = (UpdateDatasourceRequest) o;
        return Objects.equals(this.credentialDetails, updateDatasourceRequest.credentialDetails);
    }

    @Override
    public int hashCode() {
        return Objects.hash(credentialDetails);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UpdateDatasourceRequest {\n");
        sb.append("    credentialDetails: ").append(toIndentedString(credentialDetails)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
