/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 
 */
@ApiModel(description = "")
@JsonPropertyOrder({ UpdateDatasourceConnectionRequest.JSON_PROPERTY_CONNECTION_DETAILS,
        UpdateDatasourceConnectionRequest.JSON_PROPERTY_DATASOURCE_SELECTOR })

public class UpdateDatasourceConnectionRequest {
    public static final String JSON_PROPERTY_CONNECTION_DETAILS = "connectionDetails";
    private DatasourceConnectionDetails connectionDetails;

    public static final String JSON_PROPERTY_DATASOURCE_SELECTOR = "datasourceSelector";
    private Datasource datasourceSelector;

    public UpdateDatasourceConnectionRequest connectionDetails(DatasourceConnectionDetails connectionDetails) {

        this.connectionDetails = connectionDetails;
        return this;
    }

    /**
     * Get connectionDetails
     * 
     * @return connectionDetails
     **/
    @ApiModelProperty(required = true, value = "")
    @JsonProperty(JSON_PROPERTY_CONNECTION_DETAILS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public DatasourceConnectionDetails getConnectionDetails() {
        return connectionDetails;
    }

    public void setConnectionDetails(DatasourceConnectionDetails connectionDetails) {
        this.connectionDetails = connectionDetails;
    }

    public UpdateDatasourceConnectionRequest datasourceSelector(Datasource datasourceSelector) {

        this.datasourceSelector = datasourceSelector;
        return this;
    }

    /**
     * Get datasourceSelector
     * 
     * @return datasourceSelector
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_DATASOURCE_SELECTOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Datasource getDatasourceSelector() {
        return datasourceSelector;
    }

    public void setDatasourceSelector(Datasource datasourceSelector) {
        this.datasourceSelector = datasourceSelector;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateDatasourceConnectionRequest updateDatasourceConnectionRequest = (UpdateDatasourceConnectionRequest) o;
        return Objects.equals(this.connectionDetails, updateDatasourceConnectionRequest.connectionDetails)
                && Objects.equals(this.datasourceSelector, updateDatasourceConnectionRequest.datasourceSelector);
    }

    @Override
    public int hashCode() {
        return Objects.hash(connectionDetails, datasourceSelector);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UpdateDatasourceConnectionRequest {\n");
        sb.append("    connectionDetails: ").append(toIndentedString(connectionDetails)).append("\n");
        sb.append("    datasourceSelector: ").append(toIndentedString(datasourceSelector)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
