/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Power BI dataset parameter update request
 */
@ApiModel(description = "Power BI dataset parameter update request")
@JsonPropertyOrder({ UpdateMashupParametersRequest.JSON_PROPERTY_UPDATE_DETAILS })

public class UpdateMashupParametersRequest {
    public static final String JSON_PROPERTY_UPDATE_DETAILS = "updateDetails";
    private List<UpdateMashupParameterDetails> updateDetails = new ArrayList<>();

    public UpdateMashupParametersRequest updateDetails(List<UpdateMashupParameterDetails> updateDetails) {

        this.updateDetails = updateDetails;
        return this;
    }

    public UpdateMashupParametersRequest addUpdateDetailsItem(UpdateMashupParameterDetails updateDetailsItem) {
        this.updateDetails.add(updateDetailsItem);
        return this;
    }

    /**
     * The dataset parameter list to update
     * 
     * @return updateDetails
     **/
    @ApiModelProperty(required = true, value = "The dataset parameter list to update")
    @JsonProperty(JSON_PROPERTY_UPDATE_DETAILS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public List<UpdateMashupParameterDetails> getUpdateDetails() {
        return updateDetails;
    }

    public void setUpdateDetails(List<UpdateMashupParameterDetails> updateDetails) {
        this.updateDetails = updateDetails;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateMashupParametersRequest updateMashupParametersRequest = (UpdateMashupParametersRequest) o;
        return Objects.equals(this.updateDetails, updateMashupParametersRequest.updateDetails);
    }

    @Override
    public int hashCode() {
        return Objects.hash(updateDetails);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UpdateMashupParametersRequest {\n");
        sb.append("    updateDetails: ").append(toIndentedString(updateDetails)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
