/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A Power BI workbook
 */
@ApiModel(description = "A Power BI workbook")
@JsonPropertyOrder({ Workbook.JSON_PROPERTY_NAME, Workbook.JSON_PROPERTY_DATASET_ID })

public class Workbook {
    public static final String JSON_PROPERTY_NAME = "name";
    private String name;

    public static final String JSON_PROPERTY_DATASET_ID = "datasetId";
    private String datasetId;

    public Workbook name(String name) {

        this.name = name;
        return this;
    }

    /**
     * The workbook name
     * 
     * @return name
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The workbook name")
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Workbook datasetId(String datasetId) {

        this.datasetId = datasetId;
        return this;
    }

    /**
     * DatasetId for workbooks. Only applies for workbooks that has an associated
     * dataset.
     * 
     * @return datasetId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "DatasetId for workbooks. Only applies for workbooks that has an associated dataset.")
    @JsonProperty(JSON_PROPERTY_DATASET_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDatasetId() {
        return datasetId;
    }

    public void setDatasetId(String datasetId) {
        this.datasetId = datasetId;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Workbook workbook = (Workbook) o;
        return Objects.equals(this.name, workbook.name) && Objects.equals(this.datasetId, workbook.datasetId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, datasetId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Workbook {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    datasetId: ").append(toIndentedString(datasetId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
