/*
 * Power BI Client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cl.cc.powerbi.client.model;

import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Power BI workspace assignment status to capacity response
 */
@ApiModel(description = "Power BI workspace assignment status to capacity response")
@JsonPropertyOrder({ WorkspaceCapacityAssignmentStatus.JSON_PROPERTY_STATUS,
        WorkspaceCapacityAssignmentStatus.JSON_PROPERTY_START_TIME,
        WorkspaceCapacityAssignmentStatus.JSON_PROPERTY_END_TIME,
        WorkspaceCapacityAssignmentStatus.JSON_PROPERTY_CAPACITY_ID,
        WorkspaceCapacityAssignmentStatus.JSON_PROPERTY_ACTIVITY_ID })

public class WorkspaceCapacityAssignmentStatus {
    /**
     * Workspace assignment status
     */
    public enum StatusEnum {
        PENDING("Pending"),

        INPROGRESS("InProgress"),

        COMPLETEDSUCCESSFULLY("CompletedSuccessfully"),

        ASSIGNMENTFAILED("AssignmentFailed");

        private String value;

        StatusEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static StatusEnum fromValue(String value) {
            for (StatusEnum b : StatusEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_STATUS = "status";
    private StatusEnum status;

    public static final String JSON_PROPERTY_START_TIME = "startTime";
    private OffsetDateTime startTime;

    public static final String JSON_PROPERTY_END_TIME = "endTime";
    private OffsetDateTime endTime;

    public static final String JSON_PROPERTY_CAPACITY_ID = "capacityId";
    private UUID capacityId;

    public static final String JSON_PROPERTY_ACTIVITY_ID = "activityId";
    private UUID activityId;

    public WorkspaceCapacityAssignmentStatus status(StatusEnum status) {

        this.status = status;
        return this;
    }

    /**
     * Workspace assignment status
     * 
     * @return status
     **/
    @ApiModelProperty(required = true, value = "Workspace assignment status")
    @JsonProperty(JSON_PROPERTY_STATUS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public StatusEnum getStatus() {
        return status;
    }

    public void setStatus(StatusEnum status) {
        this.status = status;
    }

    public WorkspaceCapacityAssignmentStatus startTime(OffsetDateTime startTime) {

        this.startTime = startTime;
        return this;
    }

    /**
     * Start time of workspace assignment operation
     * 
     * @return startTime
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Start time of workspace assignment operation")
    @JsonProperty(JSON_PROPERTY_START_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getStartTime() {
        return startTime;
    }

    public void setStartTime(OffsetDateTime startTime) {
        this.startTime = startTime;
    }

    public WorkspaceCapacityAssignmentStatus endTime(OffsetDateTime endTime) {

        this.endTime = endTime;
        return this;
    }

    /**
     * End time of workspace assignment operation
     * 
     * @return endTime
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "End time of workspace assignment operation")
    @JsonProperty(JSON_PROPERTY_END_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getEndTime() {
        return endTime;
    }

    public void setEndTime(OffsetDateTime endTime) {
        this.endTime = endTime;
    }

    public WorkspaceCapacityAssignmentStatus capacityId(UUID capacityId) {

        this.capacityId = capacityId;
        return this;
    }

    /**
     * The capacity id
     * 
     * @return capacityId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The capacity id")
    @JsonProperty(JSON_PROPERTY_CAPACITY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UUID getCapacityId() {
        return capacityId;
    }

    public void setCapacityId(UUID capacityId) {
        this.capacityId = capacityId;
    }

    public WorkspaceCapacityAssignmentStatus activityId(UUID activityId) {

        this.activityId = activityId;
        return this;
    }

    /**
     * The activity id of the acctual assignment operation, can be provided in case
     * of assignment failures
     * 
     * @return activityId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The activity id of the acctual assignment operation, can be provided in case of assignment failures")
    @JsonProperty(JSON_PROPERTY_ACTIVITY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UUID getActivityId() {
        return activityId;
    }

    public void setActivityId(UUID activityId) {
        this.activityId = activityId;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        WorkspaceCapacityAssignmentStatus workspaceCapacityAssignmentStatus = (WorkspaceCapacityAssignmentStatus) o;
        return Objects.equals(this.status, workspaceCapacityAssignmentStatus.status)
                && Objects.equals(this.startTime, workspaceCapacityAssignmentStatus.startTime)
                && Objects.equals(this.endTime, workspaceCapacityAssignmentStatus.endTime)
                && Objects.equals(this.capacityId, workspaceCapacityAssignmentStatus.capacityId)
                && Objects.equals(this.activityId, workspaceCapacityAssignmentStatus.activityId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(status, startTime, endTime, capacityId, activityId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class WorkspaceCapacityAssignmentStatus {\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
        sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
        sb.append("    capacityId: ").append(toIndentedString(capacityId)).append("\n");
        sb.append("    activityId: ").append(toIndentedString(activityId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
